apiVersion: v1
kind: Service
metadata:
  # service name must be `maya-apiserver-service` until a time when the serivce name is not hardcoded in the provisioner.
  # See https://git.io/vNBGa
  name: maya-apiserver-service
  labels:
    app: {{ template "openebs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: apiserver
spec:
  ports:
  - name: api
    port: {{ .Values.apiserver.ports.externalPort }}
    targetPort: {{ .Values.apiserver.ports.internalPort }}
    protocol: TCP
  selector:
    app: {{ template "openebs.name" . }}
    release: {{ .Release.Name }}
    component: {{ template "openebs.fullname" . }}
    role: apiserver
  sessionAffinity: None
